add_subdirectory(core)
add_subdirectory(platform)
add_subdirectory(integration)
add_subdirectory(app)
add_subdirectory(config)
add_subdirectory(ui)
add_subdirectory(utils)

set(SHOCKERLINK_APP_SOURCES
    ${CMAKE_CURRENT_SOURCE_DIR}/main.cpp
    ${SHOCKERLINK_CORE_SOURCES}
    ${SHOCKERLINK_PLATFORM_SOURCES}
    ${SHOCKERLINK_INTEGRATION_SOURCES}
    ${SHOCKERLINK_APP_LAYER_SOURCES}
    ${SHOCKERLINK_CONFIG_SOURCES}
    ${SHOCKERLINK_UI_SOURCES}
    ${SHOCKERLINK_UTILS_SOURCES}
    PARENT_SCOPE
)

set(SHOCKERLINK_APP_INCLUDE_DIRS
    ${CMAKE_CURRENT_SOURCE_DIR}
    ${SHOCKERLINK_CORE_INCLUDE_DIRS}
    ${SHOCKERLINK_PLATFORM_INCLUDE_DIRS}
    ${SHOCKERLINK_INTEGRATION_INCLUDE_DIRS}
    ${SHOCKERLINK_APP_LAYER_INCLUDE_DIRS}
    ${SHOCKERLINK_CONFIG_INCLUDE_DIRS}
    ${SHOCKERLINK_UI_INCLUDE_DIRS}
    ${SHOCKERLINK_UTILS_INCLUDE_DIRS}
    PARENT_SCOPE
)
