name: Build Windows
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 'a42af01b72c28a8e1d7b48107b33e4f286a55ef6'
      - uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: CMakeLists.txt
          configurePreset: 'windows-release'
          buildPreset: 'windows-release'